#pragma once

#ifndef SMVTKMARKERHANDLEREPRESENTATION_H
#define SMVTKMARKERHANDLEREPRESENTATION_H

#include "smGUILibraryDefines.h"
#include <vtkPointHandleRepresentation2D.h>

class smvtkMarkerData;

/////////////////////////////////////////////////////////////////////////////////////////

/**
 *	\brief 
 *	This class represents a handle.
 *
 *	\details
 *	This class is used to represent a vtkHandleWidget. It represents a position in 2D 
 *	world coordinates using a x-y cursor (the cursor defined by an instance of 
 *	vtkPolyData and generated by a vtkPolyDataAlgorithm).
 *
 *	\sa smMarkWidget, smvtkSeedRepresentation
 */

class smGUI_EXPORT smvtkMarkerHandleRepresentation : public vtkPointHandleRepresentation2D
{
public:
	// Description:
	// Instantiate this class.
	static smvtkMarkerHandleRepresentation *New();

	// Description:
	// Standard methods for instances of this class.
#if VTK_MAJOR_VERSION < 6
	vtkTypeRevisionMacro(smvtkMarkerHandleRepresentation,vtkPointHandleRepresentation2D);
#else
	vtkTypeMacro(smvtkMarkerHandleRepresentation, vtkPointHandleRepresentation2D);
#endif
	
public:

	smvtkMarkerData*	getMarkerData();
	void				setMarkerData(smvtkMarkerData* pMarkerData);
	void				PrintSelf(ostream& os, vtkIndent indent);
	
public:
	 virtual int	ComputeInteractionState(int X, int Y, int modify=0);

protected:
	smvtkMarkerHandleRepresentation();
	virtual ~smvtkMarkerHandleRepresentation();
private:
	class	smPrivate;
	smPrivate* m_pPrivate;
};

/////////////////////////////////////////////////////////////////////////////////////////

#endif // SMVTKMARKERHANDLEREPRESENTATION_H

